# Generated by Django 4.1.3 on 2022-12-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopWord',
            fields=[
                ('word', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'parts_description_top_5_words',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW parts_description_top_5_words AS
                SELECT word, nentry as count
                FROM ts_stat('SELECT to_tsvector(description) FROM parts_part') 
                ORDER BY nentry DESC
                LIMIT 100
            """,
            "DROP MATERIALIZED VIEW parts_description_top_5_words;"
        )
    ]
